airbnb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
import core

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path('users', include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home")
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login", views.LoginView.as_view(), name="login"),
    path("signup", views.SignUpView.as_view(), name="signup"),
    path("verify/<str:key>", views.complete_verification, name="complete_verification"),
    path("login/github", views.github_login, name="github_login"),
    path("login/github/callback", views.github_callback, name="github_callback"),
    path("login/kakao", views.kakao_login, name="kakao_login"),
    path("login/kakao/callback", views.kakao_callback, name="kakao_callback"),
]

templates/partials/footer.html
<footer>
    &copy; Airbnb
</footer>

templates/partials/header.html
<header>
    <a href="/">Airbnb</a>
    <ul>
         {% include 'partials/social_login.html' %}
        <li><a href=""> Login </a></li>
    </ul>
</header>

templates/partials/nav.html
<a href="{% url "core:home" %}">Airbnb</a>
<ul>
    <li><a></a></li>
</ul>

templates/partials/social_login.html
<div>
    <a href="{% url 'users:github_login' %}">
        Continue with github
    </a>
    <a  href="{% url 'users:kakao_login' %}">
        Continue with KaKao
    </a>
</div>